import { BankTransaction } from '@/types';

export const DEMO_BANK_TRANSACTIONS: BankTransaction[] = [
  {
    id: 'btx-1',
    organization_id: 'org-empresa-1',
    date: '2026-09-10',
    description: 'COMPRA REDCOMPRA COPEC ESTACION LAS CONDES',
    amount: 42000,
    operation_number: 'OP-981240',
    bank_name: 'Banco de Chile',
    account_name: 'Cuenta Corriente SpA *4920',
    status: 'unmatched',
  },
  {
    id: 'btx-2',
    organization_id: 'org-empresa-1',
    date: '2026-09-09',
    description: 'TRANSFERENCIA A TERCEROS COMERCIAL PRAT SPA',
    amount: 85000,
    operation_number: 'TRF-341902',
    bank_name: 'Banco de Chile',
    account_name: 'Cuenta Corriente SpA *4920',
    status: 'unmatched',
  },
  {
    id: 'btx-3',
    organization_id: 'org-empresa-1',
    date: '2026-09-08',
    description: 'COMPRA TARJETA DEBITO LIDER EXPRESS PROVIDENCIA',
    amount: 45400,
    operation_number: 'TBK-110294',
    bank_name: 'Banco de Chile',
    account_name: 'Cuenta Corriente SpA *4920',
    status: 'unmatched',
  },
  {
    id: 'btx-4',
    organization_id: 'org-empresa-1',
    date: '2026-09-07',
    description: 'COMPRA TARJETA CREDITO SODIMAC HOMECENTER PQUE ARAUCO',
    amount: 100000,
    operation_number: 'TBK-481902',
    bank_name: 'Banco de Chile',
    account_name: 'Cuenta Corriente SpA *4920',
    status: 'unmatched',
  },
  {
    id: 'btx-5',
    organization_id: 'org-empresa-1',
    date: '2026-09-05',
    description: 'CARGO INTERNACIONAL DIGITAL ADOBE SYSTEMS IRELAND',
    amount: 58900,
    operation_number: 'INT-883192',
    bank_name: 'Banco de Chile',
    account_name: 'Cuenta Corriente SpA *4920',
    status: 'unmatched',
  },
  {
    id: 'btx-6',
    organization_id: 'org-empresa-1',
    date: '2026-09-11',
    description: 'CARGO MENSUAL MANTENCION CUENTA CORRIENTE SPA',
    amount: 14500,
    operation_number: 'COM-001923',
    bank_name: 'Banco de Chile',
    account_name: 'Cuenta Corriente SpA *4920',
    status: 'unmatched',
  },
  {
    id: 'btx-7',
    organization_id: 'org-empresa-1',
    date: '2026-09-04',
    description: 'PAGO AUTOMATICO GOOGLE CLOUD & WORKSPACE',
    amount: 22400,
    operation_number: 'PAT-771204',
    bank_name: 'Banco de Chile',
    account_name: 'Cuenta Corriente SpA *4920',
    status: 'unmatched',
  },
  {
    id: 'btx-8',
    organization_id: 'org-empresa-1',
    date: '2026-09-03',
    description: 'RETIRO EN CAJERO AUTOMATICO REDBANC SANTIAGO',
    amount: 50000,
    operation_number: 'ATM-102934',
    bank_name: 'Banco de Chile',
    account_name: 'Cuenta Corriente SpA *4920',
    status: 'unmatched',
  },
  {
    id: 'btx-9',
    organization_id: 'org-personal',
    date: '2026-09-08',
    description: 'COMPRA TARJETA DEBITO LIDER EXPRESS PROVIDENCIA',
    amount: 45400,
    operation_number: 'TBK-990182',
    bank_name: 'Banco Santander',
    account_name: 'Cuenta Corriente Personal *8812',
    status: 'unmatched',
  },
  {
    id: 'btx-10',
    organization_id: 'org-personal',
    date: '2026-09-04',
    description: 'PAGO CUENTA SERVICIOS ENEL DISTRIBUCION',
    amount: 32000,
    operation_number: 'PAT-661891',
    bank_name: 'Banco Santander',
    account_name: 'Cuenta Corriente Personal *8812',
    status: 'unmatched',
  }
];
