import { ExpenseDocument, ExpenseItem, Category, MonthlyBudget } from '@/types';

export const INITIAL_CATEGORIES: Category[] = [
  // Empresa
  { id: 'cat-1', name: 'Hosting y dominios', type: 'business', icon: 'Server', color: '#3B82F6', is_active: true, is_system: true, created_at: '', updated_at: '' },
  { id: 'cat-2', name: 'Software y suscripciones', type: 'business', icon: 'Code2', color: '#6366F1', is_active: true, is_system: true, created_at: '', updated_at: '' },
  { id: 'cat-3', name: 'Publicidad y marketing', type: 'business', icon: 'Megaphone', color: '#EC4899', is_active: true, is_system: true, created_at: '', updated_at: '' },
  { id: 'cat-4', name: 'Equipos tecnológicos', type: 'business', icon: 'Laptop', color: '#8B5CF6', is_active: true, is_system: true, created_at: '', updated_at: '' },
  { id: 'cat-5', name: 'Insumos de oficina', type: 'business', icon: 'Paperclip', color: '#10B981', is_active: true, is_system: true, created_at: '', updated_at: '' },
  { id: 'cat-6', name: 'Insumos de producción', type: 'business', icon: 'Boxes', color: '#F59E0B', is_active: true, is_system: true, created_at: '', updated_at: '' },
  { id: 'cat-7', name: 'Servicios profesionales', type: 'business', icon: 'Briefcase', color: '#14B8A6', is_active: true, is_system: true, created_at: '', updated_at: '' },
  { id: 'cat-8', name: 'Telefonía e internet', type: 'business', icon: 'Wifi', color: '#06B6D4', is_active: true, is_system: true, created_at: '', updated_at: '' },
  { id: 'cat-9', name: 'Transporte y combustible', type: 'business', icon: 'Fuel', color: '#EF4444', is_active: true, is_system: true, created_at: '', updated_at: '' },
  { id: 'cat-10', name: 'Alimentación laboral', type: 'business', icon: 'Utensils', color: '#F97316', is_active: true, is_system: true, created_at: '', updated_at: '' },
  { id: 'cat-11', name: 'Comisiones bancarias', type: 'business', icon: 'Landmark', color: '#64748B', is_active: true, is_system: true, created_at: '', updated_at: '' },
  { id: 'cat-12', name: 'Impuestos', type: 'business', icon: 'FileSpreadsheet', color: '#DC2626', is_active: true, is_system: true, created_at: '', updated_at: '' },

  // Personal
  { id: 'cat-13', name: 'Supermercado', type: 'personal', icon: 'ShoppingCart', color: '#10B981', is_active: true, is_system: true, created_at: '', updated_at: '' },
  { id: 'cat-14', name: 'Vivienda', type: 'personal', icon: 'Home', color: '#3B82F6', is_active: true, is_system: true, created_at: '', updated_at: '' },
  { id: 'cat-15', name: 'Servicios básicos', type: 'personal', icon: 'Zap', color: '#F59E0B', is_active: true, is_system: true, created_at: '', updated_at: '' },
  { id: 'cat-16', name: 'Salud', type: 'personal', icon: 'HeartPulse', color: '#EF4444', is_active: true, is_system: true, created_at: '', updated_at: '' },
  { id: 'cat-17', name: 'Educación', type: 'personal', icon: 'BookOpen', color: '#8B5CF6', is_active: true, is_system: true, created_at: '', updated_at: '' },
  { id: 'cat-18', name: 'Transporte', type: 'personal', icon: 'Car', color: '#06B6D4', is_active: true, is_system: true, created_at: '', updated_at: '' },
  { id: 'cat-19', name: 'Alimentación', type: 'personal', icon: 'UtensilsCrossed', color: '#F97316', is_active: true, is_system: true, created_at: '', updated_at: '' },
  { id: 'cat-20', name: 'Vestuario', type: 'personal', icon: 'Shirt', color: '#EC4899', is_active: true, is_system: true, created_at: '', updated_at: '' },
  { id: 'cat-21', name: 'Entretención', type: 'personal', icon: 'Film', color: '#A855F7', is_active: true, is_system: true, created_at: '', updated_at: '' },
  { id: 'cat-22', name: 'Mascotas', type: 'personal', icon: 'Dog', color: '#D97706', is_active: true, is_system: true, created_at: '', updated_at: '' },
];

export const DEMO_RECEIPTS: ExpenseDocument[] = [
  // 1. Supermercado (Personal)
  {
    id: 'doc-demo-1',
    user_id: 'user-demo-1',
    merchant_name: 'Supermercados Lider Express',
    merchant_legal_name: 'Walmart Chile S.A.',
    merchant_rut: '76.123.456-7',
    merchant_address: 'Av. Providencia 1234, Santiago',
    receipt_number: 'B-894120',
    document_type: 'boleta',
    document_date: '2026-09-08',
    document_time: '18:45',
    currency: 'CLP',
    subtotal: 48900,
    discount: 3500,
    net_amount: 38151,
    tax_amount: 7249,
    tip: 0,
    total_amount: 45400,
    business_total: 0,
    personal_total: 45400,
    expense_type: 'personal',
    payment_method: 'Tarjeta Débito',
    card_last_four: '4592',
    status: 'approved',
    ocr_confidence: 0.96,
    ai_confidence: 0.98,
    requires_human_review: false,
    file_name: 'boleta_lider_sept2026.jpg',
    created_at: '2026-09-08T18:50:00Z',
    updated_at: '2026-09-08T19:00:00Z',
    items: [
      {
        id: 'item-1-1',
        expense_document_id: 'doc-demo-1',
        category_id: 'cat-13',
        original_name: 'LECHE ENTERA COLUN 1L',
        normalized_name: 'Leche entera Colun 1 Litro (Pack 6)',
        quantity: 6,
        unit: 'litro',
        unit_price: 1100,
        discount: 600,
        line_total: 6000,
        category_name: 'Supermercado',
        expense_type: 'personal',
        business_percentage: 0,
        personal_percentage: 100,
        confidence: 0.98,
        requires_review: false,
        created_at: '',
        updated_at: '',
      },
      {
        id: 'item-1-2',
        expense_document_id: 'doc-demo-1',
        category_id: 'cat-13',
        original_name: 'ARROZ TUCAPEL G2 1KG',
        normalized_name: 'Arroz Grado 2 Tucapel 1 Kg',
        quantity: 2,
        unit: 'kg',
        unit_price: 1850,
        discount: 0,
        line_total: 3700,
        category_name: 'Supermercado',
        expense_type: 'personal',
        business_percentage: 0,
        personal_percentage: 100,
        confidence: 0.95,
        requires_review: false,
        created_at: '',
        updated_at: '',
      },
      {
        id: 'item-1-3',
        expense_document_id: 'doc-demo-1',
        category_id: 'cat-13',
        original_name: 'VARIOS ABARROTES Y FRUTAS',
        normalized_name: 'Abarrotes, frutas y verduras surtidas',
        quantity: 1,
        unit: 'unidad',
        unit_price: 35700,
        discount: 2900,
        line_total: 32800,
        category_name: 'Supermercado',
        expense_type: 'personal',
        business_percentage: 0,
        personal_percentage: 100,
        confidence: 0.92,
        requires_review: false,
        created_at: '',
        updated_at: '',
      }
    ],
  },

  // 2. Compra Insumos de Oficina (Empresa)
  {
    id: 'doc-demo-2',
    user_id: 'user-demo-1',
    merchant_name: 'Librería & Oficina Prat',
    merchant_legal_name: 'Comercial Prat SpA',
    merchant_rut: '77.890.123-K',
    merchant_address: 'Moneda 920, Santiago Centro',
    receipt_number: 'F-10294',
    document_type: 'factura',
    document_date: '2026-09-09',
    document_time: '11:20',
    currency: 'CLP',
    subtotal: 85000,
    discount: 0,
    net_amount: 71429,
    tax_amount: 13571,
    tip: 0,
    total_amount: 85000,
    business_total: 85000,
    personal_total: 0,
    expense_type: 'business',
    payment_method: 'Transferencia Bancaria',
    status: 'approved',
    ocr_confidence: 0.98,
    ai_confidence: 0.97,
    requires_human_review: false,
    file_name: 'factura_libreria_prat.pdf',
    created_at: '2026-09-09T11:30:00Z',
    updated_at: '2026-09-09T11:45:00Z',
    items: [
      {
        id: 'item-2-1',
        expense_document_id: 'doc-demo-2',
        category_id: 'cat-5',
        original_name: 'RESMA PAPEL CARTA 75GR CHAME-X (CX 5)',
        normalized_name: 'Caja Resmas Papel Carta Chamex 5 Unidades',
        quantity: 2,
        unit: 'caja',
        unit_price: 24500,
        discount: 0,
        line_total: 49000,
        category_name: 'Insumos de oficina',
        expense_type: 'business',
        business_percentage: 100,
        personal_percentage: 0,
        confidence: 0.98,
        requires_review: false,
        created_at: '',
        updated_at: '',
      },
      {
        id: 'item-2-2',
        expense_document_id: 'doc-demo-2',
        category_id: 'cat-5',
        original_name: 'PACK TONER HP LASERJET NEGRO',
        normalized_name: 'Tóner HP LaserJet Negro Compatible',
        quantity: 1,
        unit: 'unidad',
        unit_price: 36000,
        discount: 0,
        line_total: 36000,
        category_name: 'Insumos de oficina',
        expense_type: 'business',
        business_percentage: 100,
        personal_percentage: 0,
        confidence: 0.96,
        requires_review: false,
        created_at: '',
        updated_at: '',
      }
    ],
  },

  // 3. Pago de Software y Suscripción (Empresa)
  {
    id: 'doc-demo-3',
    user_id: 'user-demo-1',
    merchant_name: 'Adobe Systems Direct Chile',
    merchant_legal_name: 'Adobe Systems International',
    merchant_rut: '59.182.900-4',
    receipt_number: 'INV-CL-488912',
    document_type: 'factura',
    document_date: '2026-09-05',
    document_time: '04:12',
    currency: 'CLP',
    subtotal: 58900,
    discount: 0,
    net_amount: 49496,
    tax_amount: 9404, // IVA Digital 19%
    tip: 0,
    total_amount: 58900,
    business_total: 58900,
    personal_total: 0,
    expense_type: 'business',
    payment_method: 'Tarjeta Crédito',
    card_last_four: '8831',
    status: 'approved',
    ocr_confidence: 0.99,
    ai_confidence: 0.99,
    requires_human_review: false,
    file_name: 'adobe_cc_septiembre.pdf',
    created_at: '2026-09-05T05:00:00Z',
    updated_at: '2026-09-05T08:00:00Z',
    items: [
      {
        id: 'item-3-1',
        expense_document_id: 'doc-demo-3',
        category_id: 'cat-2',
        original_name: 'ADOBE CREATIVE CLOUD ALL APPS - PLAN MENSUAL',
        normalized_name: 'Adobe Creative Cloud Todas las Aplicaciones',
        quantity: 1,
        unit: 'licencia',
        unit_price: 58900,
        discount: 0,
        line_total: 58900,
        category_name: 'Software y suscripciones',
        expense_type: 'business',
        business_percentage: 100,
        personal_percentage: 0,
        confidence: 0.99,
        requires_review: false,
        created_at: '',
        updated_at: '',
      }
    ],
  },

  // 4. Combustible (Transporte / Empresa)
  {
    id: 'doc-demo-4',
    user_id: 'user-demo-1',
    merchant_name: 'Copec Estación Las Condes',
    merchant_legal_name: 'Compañía de Petróleos de Chile Copec S.A.',
    merchant_rut: '99.520.000-7',
    merchant_address: 'Av. Las Condes 10500, Santiago',
    receipt_number: 'B-771923',
    document_type: 'boleta',
    document_date: '2026-09-10',
    document_time: '08:30',
    currency: 'CLP',
    subtotal: 42000,
    discount: 0,
    net_amount: 35294,
    tax_amount: 6706,
    tip: 0,
    total_amount: 42000,
    business_total: 42000,
    personal_total: 0,
    expense_type: 'business',
    payment_method: 'App Muevo Copec',
    status: 'approved',
    ocr_confidence: 0.94,
    ai_confidence: 0.96,
    requires_human_review: false,
    file_name: 'copec_gasolina_95.png',
    created_at: '2026-09-10T08:35:00Z',
    updated_at: '2026-09-10T09:00:00Z',
    items: [
      {
        id: 'item-4-1',
        expense_document_id: 'doc-demo-4',
        category_id: 'cat-9',
        original_name: 'GASOLINA 95 OCTANOS ULTRA LIMPIA',
        normalized_name: 'Gasolina 95 Octanos (32.8 Litros)',
        quantity: 32.8,
        unit: 'litro',
        unit_price: 1280,
        discount: 0,
        line_total: 42000,
        category_name: 'Transporte y combustible',
        expense_type: 'business',
        business_percentage: 100,
        personal_percentage: 0,
        confidence: 0.95,
        requires_review: false,
        created_at: '',
        updated_at: '',
      }
    ],
  },

  // 5. Compra Mixta (Sodimac: Insumos de oficina empresa + Lámpara personal)
  {
    id: 'doc-demo-5',
    user_id: 'user-demo-1',
    merchant_name: 'Sodimac Homecenter Parque Arauco',
    merchant_legal_name: 'Sodimac S.A.',
    merchant_rut: '96.792.430-K',
    receipt_number: 'B-309481',
    document_type: 'boleta',
    document_date: '2026-09-07',
    document_time: '16:15',
    currency: 'CLP',
    subtotal: 100000,
    discount: 0,
    net_amount: 84034,
    tax_amount: 15966,
    tip: 0,
    total_amount: 100000,
    business_total: 65000,
    personal_total: 35000,
    expense_type: 'mixed',
    payment_method: 'Tarjeta Crédito',
    card_last_four: '1940',
    status: 'approved',
    ocr_confidence: 0.95,
    ai_confidence: 0.94,
    requires_human_review: false,
    file_name: 'sodimac_compra_mixta.jpg',
    created_at: '2026-09-07T16:20:00Z',
    updated_at: '2026-09-07T17:00:00Z',
    items: [
      {
        id: 'item-5-1',
        expense_document_id: 'doc-demo-5',
        category_id: 'cat-6',
        original_name: 'CABLE CANALETA Y CONECTORES ELECTRICOS OFICINA',
        normalized_name: 'Materiales Instalación Eléctrica Estudio',
        quantity: 1,
        unit: 'pack',
        unit_price: 65000,
        discount: 0,
        line_total: 65000,
        category_name: 'Insumos de producción',
        expense_type: 'business',
        business_percentage: 100,
        personal_percentage: 0,
        confidence: 0.94,
        requires_review: false,
        created_at: '',
        updated_at: '',
      },
      {
        id: 'item-5-2',
        expense_document_id: 'doc-demo-5',
        category_id: 'cat-14',
        original_name: 'LAMPARA DE MESA NORDICA DORMITORIO',
        normalized_name: 'Lámpara de velador nórdica',
        quantity: 1,
        unit: 'unidad',
        unit_price: 35000,
        discount: 0,
        line_total: 35000,
        category_name: 'Vivienda',
        expense_type: 'personal',
        business_percentage: 0,
        personal_percentage: 100,
        confidence: 0.93,
        requires_review: false,
        created_at: '',
        updated_at: '',
      }
    ],
  },

  // 6. Boleta con Descuento General y Promoción
  {
    id: 'doc-demo-6',
    user_id: 'user-demo-1',
    merchant_name: 'Farmacias Cruz Verde',
    merchant_legal_name: 'Farmacias Cruz Verde S.A.',
    merchant_rut: '76.452.120-3',
    receipt_number: 'B-654109',
    document_type: 'boleta',
    document_date: '2026-09-06',
    document_time: '19:10',
    currency: 'CLP',
    subtotal: 28900,
    discount: 5000,
    net_amount: 20084,
    tax_amount: 3816,
    tip: 0,
    total_amount: 23900,
    business_total: 0,
    personal_total: 23900,
    expense_type: 'personal',
    payment_method: 'Efectivo',
    status: 'approved',
    ocr_confidence: 0.93,
    ai_confidence: 0.92,
    requires_human_review: false,
    file_name: 'cruz_verde_descuento.jpg',
    created_at: '2026-09-06T19:15:00Z',
    updated_at: '2026-09-06T19:30:00Z',
    items: [
      {
        id: 'item-6-1',
        expense_document_id: 'doc-demo-6',
        category_id: 'cat-16',
        original_name: 'VITAMINAS C + ZINC PACK 60 COMPRIMIDOS',
        normalized_name: 'Suplemento Vitamina C y Zinc',
        quantity: 1,
        unit: 'frasco',
        unit_price: 28900,
        discount: 5000,
        line_total: 23900,
        category_name: 'Salud',
        expense_type: 'personal',
        business_percentage: 0,
        personal_percentage: 100,
        confidence: 0.92,
        requires_review: false,
        created_at: '',
        updated_at: '',
      }
    ],
  },

  // 7. Boleta con Ítem Ilegible (Requiere Revisión)
  {
    id: 'doc-demo-7',
    user_id: 'user-demo-1',
    merchant_name: 'Café & Restaurant El Roble',
    merchant_legal_name: 'Gastronomía El Roble Limitada',
    merchant_rut: '78.112.980-1',
    receipt_number: 'B-11029',
    document_type: 'boleta',
    document_date: '2026-09-11',
    document_time: '13:40',
    currency: 'CLP',
    subtotal: 24500,
    discount: 0,
    net_amount: 20588,
    tax_amount: 3912,
    tip: 2450, // 10% propina sugerida
    total_amount: 26950,
    business_total: 26950,
    personal_total: 0,
    expense_type: 'business',
    payment_method: 'Tarjeta Débito',
    card_last_four: '3321',
    status: 'needs_review',
    ocr_confidence: 0.72,
    ai_confidence: 0.75,
    requires_human_review: true,
    warnings: [
      'Texto con bajo contraste en ítem #2.',
      'Propina del 10% detectada automáticamente ($2.450).'
    ],
    file_name: 'boleta_almuerzo_cafe.jpg',
    created_at: '2026-09-11T14:00:00Z',
    updated_at: '2026-09-11T14:05:00Z',
    items: [
      {
        id: 'item-7-1',
        expense_document_id: 'doc-demo-7',
        category_id: 'cat-10',
        original_name: 'MENU EJECUTIVO SALMON GRILLADO',
        normalized_name: 'Almuerzo Ejecutivo Salmón con ensalada',
        quantity: 2,
        unit: 'plato',
        unit_price: 9500,
        discount: 0,
        line_total: 19000,
        category_name: 'Alimentación laboral',
        expense_type: 'business',
        business_percentage: 100,
        personal_percentage: 0,
        confidence: 0.92,
        requires_review: false,
        created_at: '',
        updated_at: '',
      },
      {
        id: 'item-7-2',
        expense_document_id: 'doc-demo-7',
        category_id: 'cat-10',
        original_name: 'BEB*** ******* (ILEGIBLE)',
        normalized_name: null,
        quantity: 2,
        unit: 'unidad',
        unit_price: 2750,
        discount: 0,
        line_total: 5500,
        category_name: 'Alimentación laboral',
        expense_type: 'business',
        business_percentage: 100,
        personal_percentage: 0,
        confidence: 0.45,
        requires_review: true,
        notes: 'Texto borroso en el comprobante térmico.',
        created_at: '',
        updated_at: '',
      }
    ],
  },

  // 8. Documento Potencialmente Duplicado
  {
    id: 'doc-demo-8',
    user_id: 'user-demo-1',
    merchant_name: 'Copec Estación Las Condes',
    merchant_legal_name: 'Compañía de Petróleos de Chile Copec S.A.',
    merchant_rut: '99.520.000-7',
    merchant_address: 'Av. Las Condes 10500, Santiago',
    receipt_number: 'B-771923',
    document_type: 'boleta',
    document_date: '2026-09-10',
    document_time: '08:30',
    currency: 'CLP',
    subtotal: 42000,
    discount: 0,
    net_amount: 35294,
    tax_amount: 6706,
    tip: 0,
    total_amount: 42000,
    business_total: 42000,
    personal_total: 0,
    expense_type: 'business',
    payment_method: 'App Muevo Copec',
    status: 'needs_review',
    ocr_confidence: 0.94,
    ai_confidence: 0.95,
    requires_human_review: true,
    warnings: [
      'Alerta: Posible documento duplicado. Mismo RUT (99.520.000-7), N° Boleta (B-771923) y Total ($42.000) detectados previamente en el sistema.'
    ],
    file_name: 'copec_gasolina_95_copia.png',
    created_at: '2026-09-11T15:30:00Z',
    updated_at: '2026-09-11T15:30:00Z',
    items: [
      {
        id: 'item-8-1',
        expense_document_id: 'doc-demo-8',
        category_id: 'cat-9',
        original_name: 'GASOLINA 95 OCTANOS ULTRA LIMPIA',
        normalized_name: 'Gasolina 95 Octanos (32.8 Litros)',
        quantity: 32.8,
        unit: 'litro',
        unit_price: 1280,
        discount: 0,
        line_total: 42000,
        category_name: 'Transporte y combustible',
        expense_type: 'business',
        business_percentage: 100,
        personal_percentage: 0,
        confidence: 0.95,
        requires_review: false,
        created_at: '',
        updated_at: '',
      }
    ],
  }
];

export const DEMO_BUDGETS: MonthlyBudget[] = [
  {
    id: 'b-1',
    user_id: 'user-demo-1',
    year: 2026,
    month: 9,
    budget_type: 'total',
    amount: 800000,
    alert_threshold_75: true,
    alert_threshold_90: true,
    alert_threshold_100: true,
    created_at: '',
    updated_at: '',
  },
  {
    id: 'b-2',
    user_id: 'user-demo-1',
    year: 2026,
    month: 9,
    budget_type: 'business',
    amount: 500000,
    alert_threshold_75: true,
    alert_threshold_90: true,
    alert_threshold_100: true,
    created_at: '',
    updated_at: '',
  },
  {
    id: 'b-3',
    user_id: 'user-demo-1',
    year: 2026,
    month: 9,
    budget_type: 'personal',
    amount: 300000,
    alert_threshold_75: true,
    alert_threshold_90: true,
    alert_threshold_100: true,
    created_at: '',
    updated_at: '',
  }
];
